sudo: false
language: ruby
rvm:
- 3.0.0
services:
- postgresql
before_script:
- psql -c 'create database Haarshouse_test;' -U postgres
test:
  adapter: postgresql
  database: Haarshouse_test
script:
- export RAILS_ENV=test
- bundle exec rake db:create db:migrate
deploy:
  provider: heroku
  api_key:
    secure: AbIvKwOTPG9DhRP1ir0T8l05KV11aQYdMJidHljoV9Cc3DQIjpbYg2LmjB44PoAqi21Ss5c5eZhWjbmMQKOs0Bs43/VQt/hQWHmvuLdKyO+sDiRkEnApWuYeat4iSxbM2Q7rjLZIw2oQmrv1mbXqBO3Mvh9pYbDu6j0GRxrArs/OvcWJqfiVvnosCTRW+jSQZUZIxMEssmO+0N6+ZvkRp9eXiTd2HliCDijfZjDiVyqX1j21zMYrmYGQYP4AmZxjK4k7/kWBQ9+g84l0f4mohA/ceQFcRULUh6RMst5SpgzPRok+8oe4Ca47YXavLHOuO7Kv0MbSLC68H+ma+GOksz9ZkLfFtXeuWbAEE2XjWrBRUBk+GJJTj6x9abFMH4CNdo6O6nU01ViCoJFPM06gDEguNOvIuRjO1GkzpC2Wa+ctNlh+5Gs2JNo7OOXEDVVByYp3ZclRxH11iDsJ2LZy2/Lmu5CyNCiwhRosZb8OjwQrZuVbk3xHnfwohU2i1jJdYPNfWRKgfavVIkPifMFmXpQO67IdgQ9LqUITAvLf4PMgbjbo05Ip4+70tOLZb2FqAqW5JP0nkxCmP72Eyfx0iAJgyTz2LR9lrEo0trbkTflMvd5GvU/lN3AmXOdMl3cPZ6Rk4qH7NtCUYSrdVK8XWJI3CRKtvEudSTMUiLaoD1E=
  app: haarshouseoftunes
  on:
    repo: pveggie/haarshouse
