# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef96873cb93fdb2fa35ffa6d2448a6fafd89814c7ee4a1736d38553a861df417a4cca152fe485c06f3155be0f58f1de7cc897b78353645ec13f460c366a7591c

test:
  secret_key_base: 2adccadd1b86c8a90773f3740f079bf8fb25216de6ab0b2d67f347575aab66808696b43aaf16842e870aec1022e46ce57a5c22d32b96d1fa31217a8b778f7ea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
