# source 'https://rubygems.org'
# ruby '3.0.0'

# gem 'rails', '~> 6.1', '>= 6.1.1'
# gem 'puma'
# gem 'pg'
# gem 'jbuilder'
gem 'redis'

# gem 'sass-rails'
gem 'jquery-rails'
gem 'uglifier' # minifies javascript
# gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'simple_form'
# gem 'autoprefixer-rails'
# gem 'haar_joke'
# gem 'haar_joke', path: '~/code/pveggie/haar_joke'
gem 'devise'
gem 'figaro'
gem 'pg_search'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'spring'
  # https://github.com/thoughtbot/factory_bot_rails
  gem 'factory_bot_rails'
  # gem 'webmock'
end

group :test do
  # https://github.com/thoughtbot/shoulda-matchers
  gem 'shoulda-matchers'
  # https://github.com/jdliss/shoulda-callback-matchers
  gem 'capybara'
  gem 'database_cleaner'
  gem 'faker'
  gem 'guard-rspec'
  gem 'launchy'
  gem 'rails-controller-testing'
  gem 'selenium-webdriver'
  gem 'shoulda-callback-matchers'
  gem 'webdrivers', '~> 4.0', require: false
end

group :production do
  gem 'rails_12factor'
end
